var tools = {
	"common": [
		{
			"itemName": "Leather bag",
			"unidentifiedItemName": "Bag",
			"texture": load("res://Assets/Tools/BagLeather.png"),
			"unIdentifiedTexture": load("res://Assets/Tools/BagLeather.png"),
			"type": "Tool",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Lockpick",
			"unidentifiedItemName": "Lockpick",
			"texture": load("res://Assets/Tools/Lockpick.png"),
			"unIdentifiedTexture": load("res://Assets/Tools/Lockpick.png"),
			"type": "Tool",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Blindfold",
			"unidentifiedItemName": "Blindfold",
			"texture": load("res://Assets/Tools/Blindfold.png"),
			"unIdentifiedTexture": load("res://Assets/Tools/Blindfold.png"),
			"type": "Tool",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Candle",
			"unidentifiedItemName": "Candle",
			"texture": load("res://Assets/Tools/Candle.png"),
			"unIdentifiedTexture": load("res://Assets/Tools/Candle.png"),
			"type": "Tool",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Credit card",
			"unidentifiedItemName": "Credit card",
			"texture": load("res://Assets/Tools/CreditCard.png"),
			"unIdentifiedTexture": load("res://Assets/Tools/CreditCard.png"),
			"type": "Tool",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		}
#		{
#			"itemName": "Fancy whistle",
#			"unidentifiedItemName": "Whistle",
#			"texture": load("res://Assets/Tools/WhistleFancy.png"),
#			"unIdentifiedTexture": load("res://Assets/Tools/WhistleFancy.png"),
#			"type": "Tool",
#			"category": null,
#			"value": null,
#			"enchantment": true,
#			"stackable": false,
#			"rarity": "Common"
#		}
	],
	"uncommon": [
		{
			"itemName": "Oil lamp",
			"unidentifiedItemName": "Lamp",
			"texture": load("res://Assets/Tools/LampOil.png"),
			"unIdentifiedTexture": load("res://Assets/Tools/LampOil.png"),
			"type": "Tool",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Pickaxe",
			"unidentifiedItemName": "Pickaxe",
			"texture": load("res://Assets/Tools/Pickaxe.png"),
			"unIdentifiedTexture": load("res://Assets/Tools/Pickaxe.png"),
			"type": "Tool",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Marker",
			"unidentifiedItemName": "Marker",
			"texture": load("res://Assets/Tools/Marker.png"),
			"unIdentifiedTexture": load("res://Assets/Tools/Marker.png"),
			"type": "Tool",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Ink bottle",
			"unidentifiedItemName": "Ink bottle",
			"texture": load("res://Assets/Tools/InkBottle.png"),
			"unIdentifiedTexture": load("res://Assets/Tools/InkBottle.png"),
			"type": "Tool",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Key",
			"unidentifiedItemName": "Key",
			"texture": load("res://Assets/Tools/Key.png"),
			"unIdentifiedTexture": load("res://Assets/Tools/Key.png"),
			"type": "Tool",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		}
	],
	"rare": [
		{
			"itemName": "Bag of disenchantment",
			"unidentifiedItemName": "Bag",
			"texture": load("res://Assets/Tools/BagOfDisenchantment.png"),
			"unIdentifiedTexture": load("res://Assets/Tools/BagLeather.png"),
			"type": "Tool",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Rare",
			"identified": false
		},
		{
			"itemName": "Bag of holding",
			"unidentifiedItemName": "Bag",
			"texture": load("res://Assets/Tools/BagOfHolding.png"),
			"unIdentifiedTexture": load("res://Assets/Tools/BagLeather.png"),
			"type": "Tool",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Rare",
			"identified": false
		},
		{
			"itemName": "Magic lamp",
			"unidentifiedItemName": "Lamp",
			"texture": load("res://Assets/Tools/LampMagic.png"),
			"unIdentifiedTexture": load("res://Assets/Tools/LampOil.png"),
			"type": "Tool",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Rare",
			"identified": false
		},
		{
			"itemName": "Magic marker",
			"unidentifiedItemName": "Marker",
			"texture": load("res://Assets/Tools/MarkerMagic.png"),
			"unIdentifiedTexture": load("res://Assets/Tools/Marker.png"),
			"type": "Tool",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Rare",
			"identified": false
		},
		{
			"itemName": "Magic key",
			"unidentifiedItemName": "Key",
			"texture": load("res://Assets/Tools/KeyMagic.png"),
			"unIdentifiedTexture": load("res://Assets/Tools/Key.png"),
			"type": "Tool",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Rare",
			"identified": false
		}
	]
}
