var scrolls = {
	"common": [
		{
			"itemName": "Official mail",
			"unidentifiedItemName": "Stamped scroll",
			"texture": load("res://Assets/Miscellaneous/Scroll.png"),
			"unIdentifiedTexture": load("res://Assets/Miscellaneous/Scroll.png"),
			"type": "Scroll",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Blank scroll",
			"unidentifiedItemName": "Blank scroll",
			"texture": load("res://Assets/Miscellaneous/Scroll.png"),
			"unIdentifiedTexture": load("res://Assets/Miscellaneous/Scroll.png"),
			"type": "Scroll",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Scroll of identify",
			"unidentifiedItemName": null,
			"texture": load("res://Assets/Miscellaneous/Scroll.png"),
			"unIdentifiedTexture": load("res://Assets/Miscellaneous/Scroll.png"),
			"type": "Scroll",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Scroll of create food",
			"unidentifiedItemName": null,
			"texture": load("res://Assets/Miscellaneous/Scroll.png"),
			"unIdentifiedTexture": load("res://Assets/Miscellaneous/Scroll.png"),
			"type": "Scroll",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Scroll of confusion",
			"unidentifiedItemName": null,
			"texture": load("res://Assets/Miscellaneous/Scroll.png"),
			"unIdentifiedTexture": load("res://Assets/Miscellaneous/Scroll.png"),
			"type": "Scroll",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		}
	],
	"uncommon": [
		{
			"itemName": "Scroll of remove curse",
			"unidentifiedItemName": null,
			"texture": load("res://Assets/Miscellaneous/Scroll.png"),
			"unIdentifiedTexture": load("res://Assets/Miscellaneous/Scroll.png"),
			"type": "Scroll",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Scroll of enchant weapon",
			"unidentifiedItemName": null,
			"texture": load("res://Assets/Miscellaneous/Scroll.png"),
			"unIdentifiedTexture": load("res://Assets/Miscellaneous/Scroll.png"),
			"type": "Scroll",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Scroll of enchant armor",
			"unidentifiedItemName": null,
			"texture": load("res://Assets/Miscellaneous/Scroll.png"),
			"unIdentifiedTexture": load("res://Assets/Miscellaneous/Scroll.png"),
			"type": "Scroll",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Scroll of destroy armor",
			"unidentifiedItemName": null,
			"texture": load("res://Assets/Miscellaneous/Scroll.png"),
			"unIdentifiedTexture": load("res://Assets/Miscellaneous/Scroll.png"),
			"type": "Scroll",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Scroll of summon critter",
			"unidentifiedItemName": null,
			"texture": load("res://Assets/Miscellaneous/Scroll.png"),
			"unIdentifiedTexture": load("res://Assets/Miscellaneous/Scroll.png"),
			"type": "Scroll",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Scroll of create potion",
			"unidentifiedItemName": null,
			"texture": load("res://Assets/Miscellaneous/Scroll.png"),
			"unIdentifiedTexture": load("res://Assets/Miscellaneous/Scroll.png"),
			"type": "Scroll",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Scroll of teleport",
			"unidentifiedItemName": null,
			"texture": load("res://Assets/Miscellaneous/Scroll.png"),
			"unIdentifiedTexture": load("res://Assets/Miscellaneous/Scroll.png"),
			"type": "Scroll",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		}
	],
#	"rare": [
#		{
#			"itemName": "Scroll of holy scripture",
#			"unidentifiedItemName": null,
#			"texture": load("res://Assets/Miscellaneous/Scroll.png"),
#			"unIdentifiedTexture": load("res://Assets/Miscellaneous/Scroll.png"),
#			"type": "Scroll",
#			"category": null,
#			"value": null,
#			"enchantment": true,
#			"stackable": false,
#			"rarity": "Rare",
#			"identified": false
#		},
#		{
#			"itemName": "Scroll of unholy scripture",
#			"unidentifiedItemName": null,
#			"texture": load("res://Assets/Miscellaneous/Scroll.png"),
#			"unIdentifiedTexture": load("res://Assets/Miscellaneous/Scroll.png"),
#			"type": "Scroll",
#			"category": null,
#			"value": null,
#			"enchantment": true,
#			"stackable": false,
#			"rarity": "Rare",
#			"identified": false
#		}
#	],
	"rare": [
		{
			"itemName": "Scroll of genocide",
			"unidentifiedItemName": null,
			"texture": load("res://Assets/Miscellaneous/Scroll.png"),
			"unIdentifiedTexture": load("res://Assets/Miscellaneous/Scroll.png"),
			"type": "Scroll",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Rare",
			"identified": false
		}
	]
}
