var runes = {
	"rare": [
		{
			"itemName": "Eario of Fleir",
			"unidentifiedItemName": "Tome labeled Fleir",
			"texture": load("res://Assets/Runes/RuneEarioFleir.png"),
			"unIdentifiedTexture": load("res://Assets/Runes/RuneEarioFleir.png"),
			"type": "Rune",
			"category": "Eario",
			"weight": 20,
			"value": "Fleir",
			"enchantable": false,
			"stackable": true
		},
		{
			"itemName": "Eario of Frost",
			"unidentifiedItemName": "Tome labeled Frost",
			"texture": load("res://Assets/Runes/RuneEarioFrost.png"),
			"unIdentifiedTexture": load("res://Assets/Runes/RuneEarioFrost.png"),
			"type": "Rune",
			"category": "Eario",
			"weight": 20,
			"value": "Frost",
			"enchantable": false,
			"stackable": true
		},
		{
			"itemName": "Eario of Thunder",
			"unidentifiedItemName": "Tome labeled Thunder",
			"texture": load("res://Assets/Runes/RuneEarioThunder.png"),
			"unIdentifiedTexture": load("res://Assets/Runes/RuneEarioThunder.png"),
			"type": "Rune",
			"category": "Eario",
			"weight": 20,
			"value": "Thunder",
			"enchantable": false,
			"stackable": true
		},
		{
			"itemName": "Eario of Gleeie'er",
			"unidentifiedItemName": "Tome labeled Gleeie'er",
			"texture": load("res://Assets/Runes/RuneEarioGleeie'er.png"),
			"unIdentifiedTexture": load("res://Assets/Runes/RuneEarioGleeie'er.png"),
			"type": "Rune",
			"category": "Eario",
			"weight": 20,
			"value": "Gleeie'er",
			"enchantable": false,
			"stackable": true
		},
		{
			"itemName": "Eario of Toxix",
			"unidentifiedItemName": "Tome labeled Toxix",
			"texture": load("res://Assets/Runes/RuneEarioToxix.png"),
			"unIdentifiedTexture": load("res://Assets/Runes/RuneEarioToxix.png"),
			"type": "Rune",
			"category": "Eario",
			"weight": 20,
			"value": "Toxix",
			"enchantable": false,
			"stackable": true
		},
		{
			"itemName": "Luirio of line",
			"unidentifiedItemName": "Stone with a line-pattern",
			"texture": load("res://Assets/Runes/RuneLuirioLine.png"),
			"unIdentifiedTexture": load("res://Assets/Runes/RuneLuirioLine.png"),
			"type": "Rune",
			"category": "Luirio",
			"weight": 20,
			"value": "Line",
			"enchantable": false,
			"stackable": true
		},
		{
			"itemName": "Luirio of cone",
			"unidentifiedItemName": "Stone with a cone-pattern",
			"texture": load("res://Assets/Runes/RuneLuirioCone.png"),
			"unIdentifiedTexture": load("res://Assets/Runes/RuneLuirioCone.png"),
			"type": "Rune",
			"category": "Luirio",
			"weight": 20,
			"value": "Cone",
			"enchantable": false,
			"stackable": true
		},
		{
			"itemName": "Luirio of adjacent",
			"unidentifiedItemName": "Stone with an adjacent-pattern",
			"texture": load("res://Assets/Runes/RuneLuirioAdjacent.png"),
			"unIdentifiedTexture": load("res://Assets/Runes/RuneLuirioAdjacent.png"),
			"type": "Rune",
			"category": "Luirio",
			"weight": 20,
			"value": "Adjacent",
			"enchantable": false,
			"stackable": true
		},
		{
			"itemName": "Luirio of point",
			"unidentifiedItemName": "Stone with a point",
			"texture": load("res://Assets/Runes/RuneLuirioPoint.png"),
			"unIdentifiedTexture": load("res://Assets/Runes/RuneLuirioPoint.png"),
			"type": "Rune",
			"category": "Luirio",
			"weight": 20,
			"value": "Point",
			"enchantable": false,
			"stackable": true
		},
		{
			"itemName": "Luirio of fourway",
			"unidentifiedItemName": "Stone with a four way -pattern",
			"texture": load("res://Assets/Runes/RuneLuirioFourWay.png"),
			"unIdentifiedTexture": load("res://Assets/Runes/RuneLuirioFourWay.png"),
			"type": "Rune",
			"category": "Luirio",
			"weight": 20,
			"value": "Fourway",
			"enchantable": false,
			"stackable": true
		},
		{
			"itemName": "Heario of gas",
			"unidentifiedItemName": "Orange mystical gate",
			"texture": load("res://Assets/Runes/RuneHearioGas.png"),
			"unIdentifiedTexture": load("res://Assets/Runes/RuneHearioGas.png"),
			"type": "Rune",
			"category": "Heario",
			"weight": 20,
			"value": "Gas",
			"enchantable": false,
			"stackable": true
		},
		{
			"itemName": "Heario of true",
			"unidentifiedItemName": "Pink mystical gate",
			"texture": load("res://Assets/Runes/RuneHearioTrue.png"),
			"unIdentifiedTexture": load("res://Assets/Runes/RuneHearioTrue.png"),
			"type": "Rune",
			"category": "Heario",
			"weight": 20,
			"value": "True",
			"enchantable": false,
			"stackable": true
		},
		{
			"itemName": "Heario of bolt",
			"unidentifiedItemName": "Yellow mystical gate",
			"texture": load("res://Assets/Runes/RuneHearioBolt.png"),
			"unIdentifiedTexture": load("res://Assets/Runes/RuneHearioBolt.png"),
			"type": "Rune",
			"category": "Heario",
			"weight": 20,
			"value": "Bolt",
			"enchantable": false,
			"stackable": true
		},
		{
			"itemName": "Heario of fragment",
			"unidentifiedItemName": "Cyan mystical gate",
			"texture": load("res://Assets/Runes/RuneHearioFragment.png"),
			"unIdentifiedTexture": load("res://Assets/Runes/RuneHearioFragment.png"),
			"type": "Rune",
			"category": "Heario",
			"weight": 20,
			"value": "Fragment",
			"enchantable": false,
			"stackable": true
		},
		{
			"itemName": "Heario of flow",
			"unidentifiedItemName": "Green mystical gate",
			"texture": load("res://Assets/Runes/RuneHearioFlow.png"),
			"unIdentifiedTexture": load("res://Assets/Runes/RuneHearioFlow.png"),
			"type": "Rune",
			"category": "Heario",
			"weight": 20,
			"value": "Flow",
			"enchantable": false,
			"stackable": true
		}
	]
}
