var gems = {
	"common": [
		{
			"itemName": "Black glass",
			"unidentifiedItemName": "Black rock",
			"texture": load("res://Assets/Gems/GemGlassBlack.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassBlack.png"),
			"type": "Gem",
			"category": null,
			"weight": 2,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Blue glass",
			"unidentifiedItemName": "Blue rock",
			"texture": load("res://Assets/Gems/GemGlassBlue.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassBlue.png"),
			"type": "Gem",
			"category": null,
			"weight": 2,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Green glass",
			"unidentifiedItemName": "Green rock",
			"texture": load("res://Assets/Gems/GemGlassGreen.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassGreen.png"),
			"type": "Gem",
			"category": null,
			"weight": 2,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Pink glass",
			"unidentifiedItemName": "Pink rock",
			"texture": load("res://Assets/Gems/GemGlassPink.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassPink.png"),
			"type": "Gem",
			"category": null,
			"weight": 2,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Red glass",
			"unidentifiedItemName": "Red rock",
			"texture": load("res://Assets/Gems/GemGlassRed.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassRed.png"),
			"type": "Gem",
			"category": null,
			"weight": 2,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Turqoise glass",
			"unidentifiedItemName": "Turqoise rock",
			"texture": load("res://Assets/Gems/GemGlassTurqoise.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassTurqoise.png"),
			"type": "Gem",
			"category": null,
			"weight": 2,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "White glass",
			"unidentifiedItemName": "White rock",
			"texture": load("res://Assets/Gems/GemGlassWhite.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassWhite.png"),
			"type": "Gem",
			"category": null,
			"weight": 2,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Yellow glass",
			"unidentifiedItemName": "Yellow rock",
			"texture": load("res://Assets/Gems/GemGlassYellow.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassYellow.png"),
			"type": "Gem",
			"category": null,
			"weight": 2,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		}
	],
	"uncommon": [
		{
			"itemName": "Black crystal",
			"unidentifiedItemName": "Black rock",
			"texture": load("res://Assets/Gems/GemCrystalBlack.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassBlack.png"),
			"type": "Gem",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Blue crystal",
			"unidentifiedItemName": "Blue rock",
			"texture": load("res://Assets/Gems/GemCrystalBlue.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassBlue.png"),
			"type": "Gem",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Green crystal",
			"unidentifiedItemName": "Green rock",
			"texture": load("res://Assets/Gems/GemCrystalGreen.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassGreen.png"),
			"type": "Gem",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Pink crystal",
			"unidentifiedItemName": "Pink rock",
			"texture": load("res://Assets/Gems/GemCrystalPink.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassPink.png"),
			"type": "Gem",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Red crystal",
			"unidentifiedItemName": "Red rock",
			"texture": load("res://Assets/Gems/GemCrystalRed.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassRed.png"),
			"type": "Gem",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Turqoise crystal",
			"unidentifiedItemName": "Turqoise rock",
			"texture": load("res://Assets/Gems/GemCrystalTurqoise.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassTurqoise.png"),
			"type": "Gem",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "White crystal",
			"unidentifiedItemName": "White rock",
			"texture": load("res://Assets/Gems/GemCrystalWhite.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassWhite.png"),
			"type": "Gem",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Yellow crystal",
			"unidentifiedItemName": "Yellow rock",
			"texture": load("res://Assets/Gems/GemCrystalYellow.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassYellow.png"),
			"type": "Gem",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Loadstone",
			"unidentifiedItemName": "Grey rock",
			"texture": load("res://Assets/Gems/GemLoadStone.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemLabradorite.png"),
			"type": "Gem",
			"category": null,
			"weight": 500,
			"value": {
				"binds": "Inventory"
			},
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		}
	],
	"rare": [
		{
			"itemName": "Apatite",
			"unidentifiedItemName": "Turqoise rock",
			"texture": load("res://Assets/Gems/GemApatite.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassTurqoise.png"),
			"type": "Gem",
			"category": null,
			"weight": 3,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Blue Topaz",
			"unidentifiedItemName": "Blue rock",
			"texture": load("res://Assets/Gems/GemBlueTopaz.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassBlue.png"),
			"type": "Gem",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Citrine",
			"unidentifiedItemName": "Yellow rock",
			"texture": load("res://Assets/Gems/GemCitrine.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassYellow.png"),
			"type": "Gem",
			"category": null,
			"weight": 2,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Labradorite",
			"unidentifiedItemName": "Grey rock",
			"texture": load("res://Assets/Gems/GemLabradorite.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemLabradorite.png"),
			"type": "Gem",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Moonstone",
			"unidentifiedItemName": "White rock",
			"texture": load("res://Assets/Gems/GemMoonstone.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassWhite.png"),
			"type": "Gem",
			"category": null,
			"weight": 8,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Morganite",
			"unidentifiedItemName": "Pink rock",
			"texture": load("res://Assets/Gems/GemMorganite.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassPink.png"),
			"type": "Gem",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Onyx",
			"unidentifiedItemName": "Black rock",
			"texture": load("res://Assets/Gems/GemOnyx.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassBlack.png"),
			"type": "Gem",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Peridot",
			"unidentifiedItemName": "Green rock",
			"texture": load("res://Assets/Gems/GemPeridot.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassGreen.png"),
			"type": "Gem",
			"category": null,
			"weight": 4,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Ruby",
			"unidentifiedItemName": "Red rock",
			"texture": load("res://Assets/Gems/GemRuby.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassRed.png"),
			"type": "Gem",
			"category": null,
			"weight": 8,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Sapphire",
			"unidentifiedItemName": "Blue rock",
			"texture": load("res://Assets/Gems/GemSapphire.png"),
			"unIdentifiedTexture": load("res://Assets/Gems/GemGlassBlue.png"),
			"type": "Gem",
			"category": null,
			"weight": 5,
			"value": null,
			"enchantable": false,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		}
	]
}
