extends Node

onready var gameConsole = $"/root/World/UI/UITheme/GameConsole"
onready var gameStats = $"/root/World/UI/UITheme/GameStats"

var gridSize = Vector2(60, 24)

enum tiles {
	EMPTY
	CORRIDOR_DUNGEON
	WALL_DUNGEON
	FLOOR_DUNGEON
	SIDEWALK
	DOWN_STAIR_DUNGEON
	UP_STAIR_DUNGEON
	DOOR_CLOSED
	DOOR_OPEN
	GRASS_SIMPLE
	SEA
	SAND
	SOIL
	WALL_SAND
	WALL_BRICK_SAND
	FLOOR_SAND
	DOWN_STAIR_SAND
	UP_STAIR_SAND
	CORRIDOR_SAND
	WALL_BOARD
	WALL_BRICK_LARGE
	BOOKCASE1
	BOOKCASE2
	BOOKCASE3
	GRASS
	GRASS_TREE
	GRASS_DARK
	GRASS_LIGHT
	GRASS_YELLOW
	REPLACEABLE1
	REPLACEABLE2
	REPLACEABLE3
	REPLACEABLE4
	REPLACEABLE5
	ROAD_DUNGEON
	VILLAGE_WALL_HORIZONTAL
	VILLAGE_WALL_CORNER
	VILLAGE_WALL_VERTICAL
	ROAD_GRASS
	WALL_BRICK_SMALL
	FLOOR_BRICK_SMALL
	VILLAGE_WALL_HALFWALL
	FLOOR_WOOD_BRICK
	GRASS_DEAD_TREE
	WALL_STONE_BRICK
	WALL_WOOD_PLANK
	FLOOR_STONE_BRICK
	WALL_CAVE
	WALL_DRAGONS_PEAK
	WALL_CAVE_DEEP
	FLOOR_CAVE
	FLOOR_DRAGONS_PEAK
	FLOOR_CAVE_DEEP
	CORRIDOR_STONE
}

var blockedTiles = [
	tiles.EMPTY,
	tiles.WALL_DUNGEON,
	tiles.WALL_SAND,
	tiles.WALL_BRICK_SAND,
	tiles.WALL_BOARD,
	tiles.WALL_BRICK_LARGE,
	tiles.BOOKCASE1,
	tiles.BOOKCASE2,
	tiles.BOOKCASE3,
	tiles.GRASS_TREE,
	tiles.REPLACEABLE1,
	tiles.REPLACEABLE2,
	tiles.REPLACEABLE3,
	tiles.REPLACEABLE4,
	tiles.REPLACEABLE5,
	tiles.VILLAGE_WALL_HORIZONTAL,
	tiles.VILLAGE_WALL_CORNER,
	tiles.VILLAGE_WALL_VERTICAL,
	tiles.WALL_BRICK_SMALL,
	tiles.VILLAGE_WALL_HALFWALL,
	tiles.GRASS_DEAD_TREE,
	tiles.WALL_STONE_BRICK,
	tiles.WALL_WOOD_PLANK,
	tiles.WALL_CAVE,
	tiles.WALL_DRAGONS_PEAK,
	tiles.WALL_CAVE_DEEP
]

enum interactables {
	LOCKED
	HIDDEN_ITEM
	ALTAR
	PLANT
	PLANT_CARROT
	PLANT_TOMATO
	PLANT_BEAN
	PLANT_ORANGE
}

var currentDungeonLevel = 1
var currentDungeonLevelName = "Dungeon hallways 1"
var generatedLevels = 0

var levelId = 1
var itemId = 0
var critterId = 1

func isTileFree(_tileToMoveTo, grid):
	for blockingTile in blockedTiles:
		if grid[_tileToMoveTo.x][_tileToMoveTo.y].tile == blockingTile:
			return false
	return true
