var potions = {
	"common": [
		{
			"itemName": "Water potion",
			"unidentifiedItemName": "Clear potion",
			"texture": load("res://Assets/Potions/PotionRoundTransparent.png"),
			"unIdentifiedTexture": load("res://Assets/Potions/PotionRoundTransparent.png"),
			"type": "Potion",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Soda bottle",
			"unidentifiedItemName": "Juicer potion",
			"texture": load("res://Assets/Potions/PotionRoundOrange.png"),
			"unIdentifiedTexture": load("res://Assets/Potions/PotionRoundOrange.png"),
			"type": "Potion",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Potion of confusion",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Potion",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Potion of Toxix",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Potion",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		}
	],
	"uncommon": [
		{
			"itemName": "Potion of heal",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Potion",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Potion of sleep",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Potion",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Potion of blindness",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Potion",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Potion of invisibility",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Potion",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
#		{
#			"itemName": "Potion of levitation",
#			"unidentifiedItemName": null,
#			"texture": null,
#			"unIdentifiedTexture": null,
#			"type": "Potion",
#			"category": null,
#			"value": null,
#			"enchantment": true,
#			"stackable": false,
#			"rarity": "Uncommon",
#			"identified": false
#		},
		{
			"itemName": "Potion of paralysis",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Potion",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Potion of hunger",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Potion",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		}
	],
	"rare": [
		{
			"itemName": "Potion of healaga",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Potion",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Rare",
			"identified": false
		},
		{
			"itemName": "Potion of gain level",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Potion",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Rare",
			"identified": false
		},
		{
			"itemName": "Potion of up stat",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Potion",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Rare",
			"identified": false
		},
		{
			"itemName": "Potion of down stat",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Potion",
			"category": null,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Rare",
			"identified": false
		},
	]
}
