var comestibles = {
	"common": [
		{
			"itemName": "Beans",
			"unidentifiedItemName": "Beans",
			"texture": load("res://Assets/Comestibles/ComestibleBeans.png"),
			"unIdentifiedTexture": load("res://Assets/Comestibles/ComestibleBeans.png"),
			"type": "Comestible",
			"category": null,
			"weight": 25,
			"value": 200,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Carrot",
			"unidentifiedItemName": "Carrot",
			"texture": load("res://Assets/Comestibles/ComestibleCarrot.png"),
			"unIdentifiedTexture": load("res://Assets/Comestibles/ComestibleCarrot.png"),
			"type": "Comestible",
			"category": null,
			"weight": 25,
			"value": 150,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Chocolate bar",
			"unidentifiedItemName": "Chocolate bar",
			"texture": load("res://Assets/Comestibles/ComestibleChocolateBar.png"),
			"unIdentifiedTexture": load("res://Assets/Comestibles/ComestibleChocolateBar.png"),
			"type": "Comestible",
			"category": null,
			"weight": 25,
			"value": 250,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Cookie",
			"unidentifiedItemName": "Cookie",
			"texture": load("res://Assets/Comestibles/ComestibleCookie.png"),
			"unIdentifiedTexture": load("res://Assets/Comestibles/ComestibleCookie.png"),
			"type": "Comestible",
			"category": null,
			"weight": 25,
			"value": 150,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Egg",
			"unidentifiedItemName": "Egg",
			"texture": load("res://Assets/Comestibles/ComestibleEgg.png"),
			"unIdentifiedTexture": load("res://Assets/Comestibles/ComestibleEgg.png"),
			"type": "Comestible",
			"category": null,
			"weight": 25,
			"value": 25,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Orange",
			"unidentifiedItemName": "Orange",
			"texture": load("res://Assets/Comestibles/ComestibleOrange.png"),
			"unIdentifiedTexture": load("res://Assets/Comestibles/ComestibleOrange.png"),
			"type": "Comestible",
			"category": null,
			"weight": 25,
			"value": 50,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Potatoes",
			"unidentifiedItemName": "Potatoes",
			"texture": load("res://Assets/Comestibles/ComestiblePotatoes.png"),
			"unIdentifiedTexture": load("res://Assets/Comestibles/ComestiblePotatoes.png"),
			"type": "Comestible",
			"category": null,
			"weight": 25,
			"value": 50,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Tomato",
			"unidentifiedItemName": "Tomato",
			"texture": load("res://Assets/Comestibles/ComestibleTomato.png"),
			"unIdentifiedTexture": load("res://Assets/Comestibles/ComestibleTomato.png"),
			"type": "Comestible",
			"category": null,
			"weight": 25,
			"value": 50,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		}
	],
	"uncommon": [
		{
			"itemName": "Brownie",
			"unidentifiedItemName": "Brownie",
			"texture": load("res://Assets/Comestibles/ComestibleBrownie.png"),
			"unIdentifiedTexture": load("res://Assets/Comestibles/ComestibleBrownie.png"),
			"type": "Comestible",
			"category": null,
			"weight": 25,
			"value": 400,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "SPAM",
			"unidentifiedItemName": "SPAM",
			"texture": load("res://Assets/Comestibles/ComestibleSPAM.png"),
			"unIdentifiedTexture": load("res://Assets/Comestibles/ComestibleSPAM.png"),
			"type": "Comestible",
			"category": null,
			"weight": 25,
			"value": 400,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "CC ration",
			"unidentifiedItemName": "CC ration",
			"texture": load("res://Assets/Comestibles/ComestibleCCRation.png"),
			"unIdentifiedTexture": load("res://Assets/Comestibles/ComestibleCCRation.png"),
			"type": "Comestible",
			"category": null,
			"weight": 25,
			"value": 500,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "RFG Ration",
			"unidentifiedItemName": "RFG Ration",
			"texture": load("res://Assets/Comestibles/ComestibleRFGRation.png"),
			"unIdentifiedTexture": load("res://Assets/Comestibles/ComestibleRFGRation.png"),
			"type": "Comestible",
			"category": null,
			"weight": 25,
			"value": 800,
			"enchantment": true,
			"stackable": false,
			"rarity": "Common",
			"identified": false
		}
	]
}
