var comestibles = {
	"common": [
		{
			"itemName": "Apple",
			"unidentifiedItemName": "Apple",
			"texture": load("res://Assets/Comestibles/ComestibleApple.png"),
			"unidentifiedTexture": load("res://Assets/Comestibles/ComestibleApple.png"),
			"type": "Comestible",
			"category": null,
			"weight": 5,
			"value": 300,
			"enchantable": false,
			"stackable": true,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Carrot",
			"unidentifiedItemName": "Carrot",
			"texture": load("res://Assets/Comestibles/ComestibleCarrot.png"),
			"unidentifiedTexture": load("res://Assets/Comestibles/ComestibleCarrot.png"),
			"type": "Comestible",
			"category": null,
			"weight": 5,
			"value": 300,
			"enchantable": false,
			"stackable": true,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Tomato",
			"unidentifiedItemName": "Tomato",
			"texture": load("res://Assets/Comestibles/ComestibleTomato.png"),
			"unidentifiedTexture": load("res://Assets/Comestibles/ComestibleTomato.png"),
			"type": "Comestible",
			"category": null,
			"weight": 2,
			"value": 300,
			"enchantable": false,
			"stackable": true,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Cherries",
			"unidentifiedItemName": "Cherries",
			"texture": load("res://Assets/Comestibles/ComestibleCherries.png"),
			"unidentifiedTexture": load("res://Assets/Comestibles/ComestibleCherries.png"),
			"type": "Comestible",
			"category": null,
			"weight": 2,
			"value": 75,
			"enchantable": false,
			"stackable": true,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Chocolate bar",
			"unidentifiedItemName": "Chocolate bar",
			"texture": load("res://Assets/Comestibles/ComestibleChocolateBar.png"),
			"unidentifiedTexture": load("res://Assets/Comestibles/ComestibleChocolateBar.png"),
			"type": "Comestible",
			"category": null,
			"weight": 5,
			"value": 550,
			"enchantable": false,
			"stackable": true,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Cookie",
			"unidentifiedItemName": "Cookie",
			"texture": load("res://Assets/Comestibles/ComestibleCookie.png"),
			"unidentifiedTexture": load("res://Assets/Comestibles/ComestibleCookie.png"),
			"type": "Comestible",
			"category": null,
			"weight": 2,
			"value": 200,
			"enchantable": false,
			"stackable": true,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Egg",
			"unidentifiedItemName": "Egg",
			"texture": load("res://Assets/Comestibles/ComestibleEgg.png"),
			"unidentifiedTexture": load("res://Assets/Comestibles/ComestibleEgg.png"),
			"type": "Comestible",
			"category": null,
			"weight": 2,
			"value": 75,
			"enchantable": false,
			"stackable": true,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Orange",
			"unidentifiedItemName": "Orange",
			"texture": load("res://Assets/Comestibles/ComestibleOrange.png"),
			"unidentifiedTexture": load("res://Assets/Comestibles/ComestibleOrange.png"),
			"type": "Comestible",
			"category": null,
			"weight": 3,
			"value": 250,
			"enchantable": false,
			"stackable": true,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Potatoes",
			"unidentifiedItemName": "Potatoes",
			"texture": load("res://Assets/Comestibles/ComestiblePotatoes.png"),
			"unidentifiedTexture": load("res://Assets/Comestibles/ComestiblePotatoes.png"),
			"type": "Comestible",
			"category": null,
			"weight": 2,
			"value": 125,
			"enchantable": false,
			"stackable": true,
			"rarity": "Common",
			"identified": false
		}
	],
	"uncommon": [
		{
			"itemName": "Bean can",
			"unidentifiedItemName": "Bean can",
			"texture": load("res://Assets/Comestibles/ComestibleBeanCan.png"),
			"unidentifiedTexture": load("res://Assets/Comestibles/ComestibleBeanCan.png"),
			"type": "Comestible",
			"category": null,
			"weight": 20,
			"value": 1450,
			"enchantable": false,
			"stackable": true,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "Brownie",
			"unidentifiedItemName": "Brownie",
			"texture": load("res://Assets/Comestibles/ComestibleBrownie.png"),
			"unidentifiedTexture": load("res://Assets/Comestibles/ComestibleBrownie.png"),
			"type": "Comestible",
			"category": null,
			"weight": 10,
			"value": 850,
			"enchantable": false,
			"stackable": true,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "CC ration",
			"unidentifiedItemName": "CC ration",
			"texture": load("res://Assets/Comestibles/ComestibleCCRation.png"),
			"unidentifiedTexture": load("res://Assets/Comestibles/ComestibleCCRation.png"),
			"type": "Comestible",
			"category": null,
			"weight": 10,
			"value": 850,
			"enchantable": false,
			"stackable": true,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "RFG Ration",
			"unidentifiedItemName": "RFG Ration",
			"texture": load("res://Assets/Comestibles/ComestibleRFGRation.png"),
			"unidentifiedTexture": load("res://Assets/Comestibles/ComestibleRFGRation.png"),
			"type": "Comestible",
			"category": null,
			"weight": 40,
			"value": 3000,
			"enchantable": false,
			"stackable": true,
			"rarity": "Common",
			"identified": false
		},
		{
			"itemName": "SPAM",
			"unidentifiedItemName": "SPAM",
			"texture": load("res://Assets/Comestibles/ComestibleSPAM.png"),
			"unidentifiedTexture": load("res://Assets/Comestibles/ComestibleSPAM.png"),
			"type": "Comestible",
			"category": null,
			"weight": 25,
			"value": 2500,
			"enchantable": false,
			"stackable": true,
			"rarity": "Common",
			"identified": false
		}
	]
}
