var rings = {
	"uncommon": [
		{
			"itemName": "Ring of Fleir resistance",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Accessory",
			"category": "Ring",
			"weight": 10,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Ring of Frost resistance",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Accessory",
			"category": "Ring",
			"weight": 10,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Ring of Thunder resistance",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Accessory",
			"category": "Ring",
			"weight": 10,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Ring of Gleeie'er resistance",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Accessory",
			"category": "Ring",
			"weight": 10,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Ring of Toxix resistance",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Accessory",
			"category": "Ring",
			"weight": 10,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Ring of protection",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Accessory",
			"category": "Ring",
			"weight": 10,
			"value": 3,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Ring of seeing",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Accessory",
			"category": "Ring",
			"weight": 10,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Ring of hunger",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Accessory",
			"category": "Ring",
			"weight": 10,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
#		{
#			"itemName": "Ring of levitation",
#			"unidentifiedItemName": null,
#			"texture": null,
#			"unIdentifiedTexture": null,
#			"type": "Accessory",
#			"category": "Ring",
#			"weight": 10,
#			"value": null,
#			"enchantment": true,
#			"stackable": false,
#			"rarity": "Uncommon",
#			"identified": false
#		},
		{
			"itemName": "Ring of slow digestion",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Accessory",
			"category": "Ring",
			"weight": 10,
			"value": {
				"turnedOn": null
			},
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Ring of regen",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Accessory",
			"category": "Ring",
			"weight": 10,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		},
		{
			"itemName": "Ring of fumbling",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Accessory",
			"category": "Ring",
			"weight": 10,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Uncommon",
			"identified": false
		}
	],
	"rare": [
		{
			"itemName": "Ring of Strength",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Accessory",
			"category": "Ring",
			"weight": 10,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Rare",
			"identified": false
		},
		{
			"itemName": "Ring of Legerity",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Accessory",
			"category": "Ring",
			"weight": 10,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Rare",
			"identified": false
		},
		{
			"itemName": "Ring of Balance",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Accessory",
			"category": "Ring",
			"weight": 10,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Rare",
			"identified": false
		},
		{
			"itemName": "Ring of Wisdom",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Accessory",
			"category": "Ring",
			"weight": 10,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Rare",
			"identified": false
		},
		{
			"itemName": "Ring of Belief",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Accessory",
			"category": "Ring",
			"weight": 10,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Rare",
			"identified": false
		},
		{
			"itemName": "Ring of Visage",
			"unidentifiedItemName": null,
			"texture": null,
			"unIdentifiedTexture": null,
			"type": "Accessory",
			"category": "Ring",
			"weight": 10,
			"value": null,
			"enchantment": true,
			"stackable": false,
			"rarity": "Rare",
			"identified": false
		}
	]
}
